default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: ifsc_development

test:
  <<: *default
  database: ifsc_test

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: ifsc_production
  username: root
  password: Goplum2018
  host: localhost